name: weQuiz-ktlint
on:
  pull_request:
    branches:
      - main
      - dev
  push:
    paths:
      - '**.kt'
jobs:
  ktlint:
    name: ktlint check
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: ktlint
        uses: ScaCap/action-ktlint@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
