name: reviewdog
on: [pull_request]

jobs:
  ktlint:
    name: Check Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Run ktlint
        id: ktlint
        uses: ScaCap/action-ktlint@master
        with:
          github_token: ${{ secrets.github_token }}

      - name: Check Ktlint Results
        if: ${{ steps.ktlint.outputs.error_count }}
        run: |
          if [ "${{ steps.ktlint.outputs.error_count }}" -gt 0 ]; then
            echo "Ktlint found errors. Please fix them before merging."
            exit 1
          fi
